name: release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: Linux
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -Ur requirements.txt
      - name: Fetch web assets
        run: inv assets
      - name: Publish
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          rm -rf ./dist
          python -m build
          ls -lh ./dict
          rm -rf ./dist/*
          twine upload ./dist/*

