name: tests

on: [push]

jobs:
  test:
    runs-on: Linux
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          python -m pip install -Ur requirements.txt
      - name: Test with pytest
        run: | 
          coverage run --source=src/restx_monkey -m unittest discover
          coverage xml -o coverage-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: unittest-results-${{ matrix.python-version }}
          path: coverage/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}